components:
  photo:
    type: object
    fields:
      - name: image
        label: Afbeelding
        type: image
        required: true
      - name: alt
        label: Alt tekst
        type: string
        description: Een enkele regel/paar woorden die de afbeelding omschrijven
        required: true
  seo:
    type: object
    fields:
      - name: description
        label: Omschrijving
        type: string
        required: true
      - name: keywords
        label: Sleutelwoorden
        type: string
        required: false

media:
  input: public
  output: /

content:
  - name: configuration
    label: Configuratie
    type: file
    path: src/pageconfig.json
    fields:
      - name: maillist_url
        label: Maillijst link
        type: string
        required: true
        description: De link naar bijv. Google Forms waarmee mensen zich kunnen aanmelden voor de maillijst
      - name: socials
        label: Social media accounts
        type: object
        list:
          min: 1
          collapsible:
            collapsed: true
            summary: "{title}"
        fields:
          - name: title
            label: Identificatie label
            type: string
            required: false
            description: Dit komt niet op de echte website, maar wordt alleen op dit systeem gebruikt
          - name: url
            label: URL van account
            type: string
            required: true
          - name: icon
            label: Icoontje
            type: string
            required: true
            description: Zoek op "https://icon-sets.iconify.design/ic/" naar een icoontje en plak de "Icon name" hier
          - name: foreground
            label: Voorgrond kleur/stijl
            type: string
            required: false
            description: De voorgrond van het icoontje. Het makkelijkste is om gewoon een kleur als \#000000 neer te zetten, maar gradients zijn ook mogelijk (via CSS)
          - name: background
            label: Achtergrond kleur/stijl
            type: string
            required: true
            description: De achtergrond van het icoontje. Het makkelijkste is om gewoon een kleur als \#FFFFFF neer te zetten, maar gradients zijn ook mogelijk (via CSS)
  - name: nl
    label: NL pagina's
    type: group
    items:
      - name: nl-home
        label: Start
        type: file
        path: src/content/nl/index.md
        fields:
          - name: image
            label: Omslagafbeelding
            type: image
            required: true
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: nl-faq
        label: FAQ (Vaak gestelde vragen)
        type: file
        path: src/content/nl/faq.md
        fields:
          - name: items
            label: Vraag/antwoord lijst
            type: object
            required: true
            list:
              min: 1
              collapsible:
                collapsed: true
                summary: "{question}"
            fields:
              - name: question
                label: Vraag
                type: string
                required: true
              - name: answer
                label: Antwoord
                type: text
                required: true
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: nl-upcomming-event
        label: Komend evenement
        type: file
        path: src/content/nl/upcomming-event.md
        fields:
          - name: image
            label: Omslagafbeelding
            type: image
            required: false
          - name: signup_url
            label: URL voor Registratie
            description: Bijvoorbeeld voor Google Forms
            type: string
            required: false
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: nl-postlist
        label: Posts overzicht
        type: file
        path: src/content/nl/post-list.md
        fields:
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: nl-posts
        label: Posts
        type: collection
        path: src/content/nl/posts
        view:
          fields: [title, kind, created_at]
        fields:
          - name: title
            label: Titel
            type: string
            required: true
          - name: kind
            label: Soort
            type: select
            required: true
            options:
              values: [Evenement, Lezing, Overig]
          - name: created_at
            label: Gemaakt op
            type: date
            required: true
          - name: image
            label: Omslagafbeelding
            type: image
            required: true
          - name: galary
            label: Galarij
            description: Als je dit leeg laat, wordt de galarij niet weergeven, maar misschien dat je dit bij evenementen dit veld wel nodig kan hebben.
            component: photo
            required: false
            list:
              collapsible:
                collapsed: true
                summary: "{alt}"
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
  - name: en
    label: EN pagina's
    type: group
    items:
      - name: en-home
        label: Start
        type: file
        path: src/content/en/index.md
        fields:
          - name: image
            label: Omslagafbeelding
            type: image
            required: true
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: en-faq
        label: FAQ (Vaak gestelde vragen)
        type: file
        path: src/content/en/faq.md
        fields:
          - name: items
            label: Vraag/antwoord lijst
            type: object
            required: true
            list:
              min: 1
              collapsible:
                collapsed: true
                summary: "{question}"
            fields:
              - name: question
                label: Vraag
                type: string
                required: true
              - name: answer
                label: Antwoord
                type: text
                required: true
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: en-upcomming-event
        label: Komend evenement
        type: file
        path: src/content/en/upcomming-event.md
        fields:
          - name: image
            label: Omslagafbeelding
            type: image
            required: false
          - name: signup_url
            label: URL voor Registratie
            description: Bijvoorbeeld voor Google Forms
            type: string
            required: false
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: en-postlist
        label: Posts overzicht
        type: file
        path: src/content/en/post-list.md
        fields:
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
      - name: en-posts
        label: Posts
        type: collection
        path: src/content/en/posts
        view:
          fields: [title, kind, created_at]
        fields:
          - name: title
            label: Titel
            type: string
            required: true
          - name: kind
            label: Soort
            type: select
            required: true
            options:
              values: [Evenement, Lezing, Overig]
          - name: created_at
            label: Gemaakt op
            type: date
            required: true
          - name: image
            label: Omslagafbeelding
            type: image
            required: true
          - name: galary
            label: Galarij
            description: Als je dit leeg laat, wordt de galarij niet weergeven, maar misschien dat je dit bij evenementen dit veld wel nodig kan hebben.
            component: photo
            required: false
            list:
              collapsible:
                collapsed: true
                summary: "{alt}"
          - name: seo
            label: SEO
            component: seo
            required: true
          - name: body
            type: rich-text
            required: true
            options:
              format: markdown
              media: false
